config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :souls do#, path_names: { edit: "soul", update: "soul" }, only: [:show, :edit, :update, :index]
    resources :projects do
      member do
        get "like", to: "projects#upvote"
        get "dislike", to: "projects#downvote"
      end
      resources :projcomments
    end
    resources :purposes do
      member do
        get "like", to: "purposes#upvote"
        get "dislike", to: "purposes#downvote"
      end
      resources :purpcomments
    end
    resources :quotations do
      member do
        get "like", to: "quotations#upvote"
        get "dislike", to: "quotations#downvote"
      end
      resources :quotycomments
    end
    resources :articles do
      member do
        get "like", to: "articles#upvote"
        get "dislike", to: "articles#downvote"
      end
      resources :artcomments
    end
    resources :wishes do
      member do
        get "like", to: "wishes#upvote"
        get "dislike", to: "wishes#downvote"
      end
      resources :wishcomments
    end
    resources :hobbies do
      member do
        get "like", to: "hobbies#upvote"
        get "dislike", to: "hobbies#downvote"
      end
      resources :hobcomments
    end
    resources :experiences
    resources :resumes 
  end

  root "resumes#all_resumes"
  get 'soul_resumes', to: 'resumes#show'

  get 'home', to: 'souls#home'
  get 'cabinet', to: 'souls#cabinet'
  get 'organizer', to: 'souls#organizer'
  get 'all_resumes', to: 'resumes#all_resumes'
  get 'resumes', to: 'resumes#all_resumes'

end

app/models/wish.rb
class Wish < ActiveRecord::Base
  acts_as_votable
  
  belongs_to :soul
  has_many :wishcomments

  has_attached_file :imgwish, styles: { large: "300x300#", medium: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imgwish, content_type: /\Aimage\/.*\Z/
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
	before_action :find_soul
	before_action :find_wish, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

	def soul_all_wishes

	end

	def index
		@wishes = Wish.where(soul_id: @soul).order("created_at DESC") #.reject { |p| p.id == @wish.id}
	end

	def new
		@wish = @soul.wishes.new
	end

	def create
		@wish = @soul.wishes.new wish_params	
		if @wish.save
			redirect_to soul_wish_path(@soul, @wish)
		else
			render 'new'
		end	
	end

	def show
		@wishes = Wish.where(soul_id: @soul).order("created_at DESC")  
		@wishcomments = Wishcomment.where(wish_id: @wish)
	end

	def edit
		
	end

	def update
		if @wish.update wish_params
			redirect_to soul_wish_path(@soul, @wish), notice: "wish was succesfully updated!" 
		else
			render 'edit'
		end
	end

	def destroy
		@wish.destroy
		redirect_to soul_wishes_path(@soul)
	end

		def upvote
			@wish.upvote_by current_user
			redirect_to :back
		end

		def downvote
			@wish.downvote_from current_user
			redirect_to :back
		end

	private

	def wish_params
		params.require(:wish).permit(:title, :description, :url, :imgwish)
	end

	def find_soul
		@soul = Soul.find(params[:soul_id])
	end

	def find_wish
		@wish = Wish.find(params[:id])
		#@soul = Soul.find(params[:soul_id])
		#@wish = @soul.wishes.find(params[:id])
		#@wish = wish.find_by(soul_id: params[:wish_id])
		#@wish = @soul.wishes.where(id: params[:id])
		#@message.comments.where(id: params[:id])
	end
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/wishes/_wishes_form.html.haml
.bodybackg
  .col-xs-1.col-md-1
    .btn_back
    = link_to "Back", root_path, class: "btn btn-default"
  .col-xs-10.col-md-10
    .tit_desc_img_block
      = simple_form_for ([@soul, @wish]), html: { multipart: true } do |f|
        - if @soul.errors.any?
          #errors
            %p
              = @wish.errors.count
              Prevented this wish froms saving
            %ul
              - @wish.errors.full_messages.each do |msg|
                %li= msg
        .panel-body
          = f.input :title, label: 'wish Name', input_html: { title: "NAME of your wish", class: 'form-control'}
          = f.input :description, label: 'wish description', input_html: { class: 'form-control'}
          = f.input :url, label: 'Link', input_html: { title: "NAME of your wish", class: 'form-control'}
          = f.input :imgwish, label: 'Attach an image that will be in this wish', input_html: { class: 'form-control'}
   
        .sub_button
          = f.button :submit, class: "btn btn-primary sub_button"
        .btn_bottom_back
          = link_to "Back", root_path, class: "btn btn-default btn_bottom_back"
  .col-xs-1.col-md-1
  %br

app/views/wishes/edit.html.haml
.caption
  %h1 Edit yuore wish
  
= render 'wishes_form'

app/views/wishes/index.html.haml
.body_suits_show
  .col-xs-1.col-md-1
    %br
    = link_to "new", new_soul_wish_path, class: "btn btn-default btn_bottom_back"
  .col-xs-10.col-md-10
    - @wishes.each do |wi|
      .user_plate
        .col-xs-3.col-md-3
          .suit
            .suits_fotos
              %h2= link_to wi.title, soul_wish_path(@soul, wi)#(@wishs, @soul)
              %h4
                = wi.wishcomments.count
                Comments
        .col-xs-3.col-md-3
        .col-xs-3.col-md-3
        .col-xs-3.col-md-3


  .col-xs-1.col-md-1

app/views/wishes/new.html.haml
.caption
  %h1 New Wish
  
= render 'wishes_form'

app/views/wishes/show.html.haml
.bodybackg
  %h1 this is the face of user, like a person status
  %h2= @wish.title
  %br
  %h3= link_to @soul.name, soul_path(@soul)
  %br
  = link_to "new", new_soul_wish_path, class: "btn btn-default btn_bottom_back"
  = link_to "delete", soul_wish_path(@soul, @wish), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default btn_bottom_back"
  .co
    %p
      =@wish.get_upvotes.size
      Likes
    %p
      =@wish.get_downvotes.size
      Likes
    =link_to "Like", like_soul_wish_path(@soul, @wish), method: :get
    =link_to "Dislike", dislike_soul_wish_path(@soul, @wish), method: :get
  .body_wish_show
    .col-xs-1.col-md-1
      %p
        =@wish.get_upvotes.size
        Likes
      %p
        =@wish.get_downvotes.size
        Likes
      =link_to "Like", like_soul_wish_path, method: :get
      =link_to "Dislike", dislike_soul_wish_path, method: :get

    .col-xs-6.col-md-6
      - @wishes.each do |wi|
        .user_plate
          .col-xs-3.col-md-3
            .suit
              .suits_fotos
                %h2= link_to wi.title, soul_wish_path(@soul, wi)
                %h2= truncate(wi.description, length: 5)
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3


    .col-xs-5.col-md-5
      #comments
        %h2.comment_count= pluralize(@wish.wishcomments.count, "Comment")
        - @wishcomments.each do |wis|
          .comment
            %p
              = wis.soul.name
              = wis.wishcontent
        = render "wishcomments/form"


  - if @soul.user == current_user
    = link_to "edit", edit_soul_wish_path, class: "btn btn-default btn_bottom_back"

app/views/wishes/soul_all_projects.html.haml
.body_suits_show
  .col-xs-1.col-md-1

  .col-xs-10.col-md-10
    - @projects.each do |project|
      .user_plate
          .col-xs-3.col-md-3
            .suit
              .suits_fotos
                  %h2= link_to project.title, soul_project_path(@soul, @project)
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3


  .col-xs-1.col-md-1

app/views/wishes/soul_all_wishes.html.haml
.body_suits_show
  .col-xs-1.col-md-1

  .col-xs-10.col-md-10
    - @wishes.each do |wi|
      .user_plate
          .col-xs-3.col-md-3
            .suit
              .suits_fotos
                  %h2= link_to wi.title, soul_wish_path(@soul, wi)
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3


  .col-xs-1.col-md-1