config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :souls do#, path_names: { edit: "soul", update: "soul" }, only: [:show, :edit, :update, :index]
    resources :projects do
      member do
        get "like", to: "projects#upvote"
        get "dislike", to: "projects#downvote"
      end
      resources :projcomments
    end
    resources :purposes do
      member do
        get "like", to: "purposes#upvote"
        get "dislike", to: "purposes#downvote"
      end
      resources :purpcomments
    end
    resources :quotations do
      member do
        get "like", to: "quotations#upvote"
        get "dislike", to: "quotations#downvote"
      end
      resources :quotycomments
    end
    resources :articles do
      member do
        get "like", to: "articles#upvote"
        get "dislike", to: "articles#downvote"
      end
      resources :artcomments
    end
    resources :wishes do
      member do
        get "like", to: "wishes#upvote"
        get "dislike", to: "wishes#downvote"
      end
      resources :wishcomments
    end
    resources :hobbies do
      member do
        get "like", to: "hobbies#upvote"
        get "dislike", to: "hobbies#downvote"
      end
      resources :hobcomments
    end
    resources :experiences
    resources :resumes 
  end

  root "resumes#all_resumes"
  get 'soul_resumes', to: 'resumes#show'

  get 'home', to: 'souls#home'
  get 'cabinet', to: 'souls#cabinet'
  get 'organizer', to: 'souls#organizer'
  get 'all_resumes', to: 'resumes#all_resumes'
  get 'resumes', to: 'resumes#all_resumes'

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_votable
  
  belongs_to :soul
  has_many :artcomments

  has_attached_file :imgarticle, styles: { large: "300x300#", medium: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imgarticle, content_type: /\Aimage\/.*\Z/
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :find_soul
	before_action :find_article, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

	def soul_all_articles

	end

	def index
		@articles = Article.where(soul_id: @soul).order("created_at DESC") #.reject { |p| p.id == @article.id}
	end

	def new
		@article = @soul.articles.new
	end

	def create
		@article = @soul.articles.new article_params	
		if @article.save
			redirect_to soul_article_path(@soul, @article)
		else
			render 'new'
		end	
	end

	def show
		@articles = Article.where(soul_id: @soul).order("created_at DESC")  
		@artcomments = Artcomment.where(article_id: @article)
	end

	def edit
		
	end

	def update
		if @article.update article_params
			redirect_to soul_article_path(@soul, @article), notice: "article was succesfully updated!" 
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to soul_articles_path(@soul)
	end

		def upvote
			@article.upvote_by current_user
			redirect_to :back
		end

		def downvote
			@article.downvote_from current_user
			redirect_to :back
		end	


	private

	def article_params
		params.require(:article).permit(:title, :description, :url, :imgarticle)
	end

	def find_soul
		@soul = Soul.find(params[:soul_id])
	end

	def find_article
		@article = Article.find(params[:id])
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles_form.html.haml
.bodybackg
  .col-xs-1.col-md-1
    .btn_back
    = link_to "Back", root_path, class: "btn btn-default"
  .col-xs-10.col-md-10
    .tit_desc_img_block
      = simple_form_for ([@soul, @article]), html: { multipart: true } do |f|
        - if @soul.errors.any?
          #errors
            %p
              = @article.errors.count
              Prevented this article froms saving
            %ul
              - @article.errors.full_messages.each do |msg|
                %li= msg
        .panel-body
          = f.input :title, label: 'article Name', input_html: { title: "NAME of your article", class: 'form-control'}
          = f.input :description, label: 'article description', input_html: { class: 'form-control'}
          = f.input :url, label: 'Link', input_html: { title: "NAME of your article", class: 'form-control'}
          = f.input :imgarticle, label: 'Attach an image that will be in this article', input_html: { class: 'form-control'}
        .sub_button
          = f.button :submit, class: "btn btn-primary sub_button"
        .btn_bottom_back
          = link_to "Back", root_path, class: "btn btn-default btn_bottom_back"
  .col-xs-1.col-md-1
  %br

app/views/articles/edit.html.haml
.caption
  %h1 Edit Article
  
= render 'articles_form'

app/views/articles/index.html.haml
.body_suits_show
  .col-xs-1.col-md-1
    %br
    = link_to "new", new_soul_article_path, class: "btn btn-default btn_bottom_back"
  .col-xs-10.col-md-10
    - @articles.each do |art|
      .user_plate
        .col-xs-3.col-md-3
          .suit
            .suits_fotos
              %h2= link_to art.title, soul_article_path(@soul, art)
              %h4
                = art.artcomments.count
                Comments
        .col-xs-3.col-md-3
        .col-xs-3.col-md-3
        .col-xs-3.col-md-3


  .col-xs-1.col-md-1

app/views/articles/new.html.haml
.caption
  %h1 New Article
  
= render 'articles_form'

app/views/articles/show.html.haml
.bodybackg
  %h1 this is the face of user, like a person status
  %h2= @article.title
  %br
  %h3= link_to @soul.name, soul_path(@soul)
  %br
  = link_to "new", new_soul_article_path, class: "btn btn-default btn_bottom_back"
  = link_to "delete", soul_article_path(@soul, @article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default btn_bottom_back"

  .body_article_show
    .col-xs-1.col-md-1
      %p
        =@article.get_upvotes.size
        Likes
      %p
        =@article.get_downvotes.size
        Likes
      =link_to "Like", like_soul_article_path(@soul, @article), method: :get
      =link_to "Dislike", dislike_soul_article_path(@soul, @article), method: :get

    .col-xs-10.col-md-10
      - @articles.each do |art|
        .user_plate
          .col-xs-3.col-md-3
            .suit
              .suits_fotos
                %h2= link_to art.title, soul_article_path(@soul, art)
                %h2= truncate(art.description, length: 5)
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
            #comments
              %h2.comment_count= pluralize(@article.artcomments.count, "Comment")
              - @artcomments.each do |artcomment|
                .comment
                  %p
                    = artcomment.soul.name
                    = artcomment.artcontent
            = render "artcomments/form"         


    .col-xs-1.col-md-1

  - if @soul.user == current_user
    = link_to "edit", edit_soul_article_path, class: "btn btn-default btn_bottom_back"

app/views/articles/soul_all_articles.html.haml
.body_suits_show
  .col-xs-1.col-md-1

  .col-xs-10.col-md-10
    - @articles.each do |art|
      .user_plate
          .col-xs-3.col-md-3
            .suit
              .suits_fotos
                  %h2= link_to art.title, soul_article_path(@soul, @art)
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3


  .col-xs-1.col-md-1

app/views/articles/soul_all_projects.html.haml
.body_suits_show
  .col-xs-1.col-md-1

  .col-xs-10.col-md-10
    - @projects.each do |project|
      .user_plate
          .col-xs-3.col-md-3
            .suit
              .suits_fotos
                  %h2= link_to project.title, soul_project_path(@soul, @project)
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3


  .col-xs-1.col-md-1