config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :souls do#, path_names: { edit: "soul", update: "soul" }, only: [:show, :edit, :update, :index]
    resources :projects do
      member do
        get "like", to: "projects#upvote"
        get "dislike", to: "projects#downvote"
      end
      resources :projcomments
    end
    resources :purposes do
      member do
        get "like", to: "purposes#upvote"
        get "dislike", to: "purposes#downvote"
      end
      resources :purpcomments
    end
    resources :quotations do
      member do
        get "like", to: "quotations#upvote"
        get "dislike", to: "quotations#downvote"
      end
      resources :quotycomments
    end
    resources :articles do
      member do
        get "like", to: "articles#upvote"
        get "dislike", to: "articles#downvote"
      end
      resources :artcomments
    end
    resources :wishes do
      member do
        get "like", to: "wishes#upvote"
        get "dislike", to: "wishes#downvote"
      end
      resources :wishcomments
    end
    resources :hobbies do
      member do
        get "like", to: "hobbies#upvote"
        get "dislike", to: "hobbies#downvote"
      end
      resources :hobcomments
    end
    resources :experiences
    resources :resumes 
  end

  root "resumes#all_resumes"
  get 'soul_resumes', to: 'resumes#show'

  get 'home', to: 'souls#home'
  get 'cabinet', to: 'souls#cabinet'
  get 'organizer', to: 'souls#organizer'
  get 'all_resumes', to: 'resumes#all_resumes'
  get 'resumes', to: 'resumes#all_resumes'

end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
  acts_as_votable

  belongs_to :soul
  has_many :quotycomments
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
	before_action :find_soul
	before_action :find_quotation, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

	def soul_all_quotations

	end

	def index
		@quotations = Quotation.where(soul_id: @soul).order("created_at DESC") #.reject { |p| p.id == @quotation.id}
	end

	def new
		@quotation = @soul.quotations.new
	end

	def create
		@quotation = @soul.quotations.new quotation_params	
		if @quotation.save
			redirect_to soul_quotation_path(@soul, @quotation)
		else
			render 'new'
		end	
	end

	def show
		@quotations = Quotation.where(soul_id: @soul).order("created_at DESC")  
		@quotycomments = Quotycomment.where(quotation_id: @quotation)
	end

	def edit
		
	end

	def update
		if @quotation.update quotation_params
			redirect_to soul_quotation_path(@soul, @quotation), notice: "quotation was succesfully updated!" 
		else
			render 'edit'
		end
	end

	def destroy
		@quotation.destroy
		redirect_to soul_quotations_path
	end

		def upvote
			@quotation.upvote_by current_user
			redirect_to :back
		end

		def downvote
			@quotation.downvote_from current_user
			redirect_to :back
		end

	private

	def quotation_params
		params.require(:quotation).permit(:author, :proverb, :description, :datecomment, :created)
	end

	def find_soul
		@soul = Soul.find(params[:soul_id])
	end

	def find_quotation
		@quotation = Quotation.find(params[:id])
		#@soul = Soul.find(params[:soul_id])
		#@quotation = @soul.quotations.find(params[:id])
		#@quotation = quotation.find_by(soul_id: params[:quotation_id])
		#@quotation = @soul.quotations.where(id: params[:id])
		#@message.comments.where(id: params[:id])
	end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_quotations_form.html.haml
.bodybackg
  .col-xs-1.col-md-1
    .btn_back
    = link_to "Back", root_path, class: "btn btn-default"
  .col-xs-10.col-md-10
    .tit_desc_img_block
      = simple_form_for ([@soul, @quotation]), html: { multipart: true } do |f|
        - if @soul.errors.any?
          #errors
            %p
              = @quotation.errors.count
              Prevented this quotation froms saving
            %ul
              - @quotation.errors.full_messages.each do |msg|
                %li= msg
        .panel-body
          = f.input :author, label: 'quotation author', input_html: { title: "NAME of your quotation", class: 'form-control'}
          = f.input :proverb, label: 'proverb', input_html: { class: 'form-control'}
          = f.input :description, label: 'description', input_html: { title: "NAME of your quotation", class: 'form-control'}
          = f.input :datecomment, label: 'quotation was find at:', input_html: { class: 'form-control'}
          = f.input :created, label: 'quotation date creation', input_html: { title: "NAME of your quotation", class: 'form-control'}
   
        .sub_button
          = f.button :submit, class: "btn btn-primary sub_button"
        .btn_bottom_back
          = link_to "Back", root_path, class: "btn btn-default btn_bottom_back"
  .col-xs-1.col-md-1
  %br

app/views/quotations/edit.html.haml
.caption
  %h1 Edit Quotation
  
= render 'quotations_form'

app/views/quotations/index.html.haml
.body_suits_show
  .col-xs-1.col-md-1
    %br
    = link_to "new", new_soul_quotation_path, class: "btn btn-default btn_bottom_back"
  .col-xs-10.col-md-10
    - @quotations.each do |quot|
      .user_plate
        .col-xs-3.col-md-3
          .suit
            .suits_fotos
              %h2= link_to quot.author, soul_quotation_path(@soul, quot)
              %h2= link_to quot.proverb, soul_quotation_path(@soul, quot)#(@projects, @soul)
              %h4
                = quot.quotycomments.count
                Comments
        .col-xs-3.col-md-3
        .col-xs-3.col-md-3
        .col-xs-3.col-md-3


  .col-xs-1.col-md-1

app/views/quotations/new.html.haml
.caption
  %h1 New Quotation
  
= render 'quotations_form'

app/views/quotations/show.html.haml
.bodybackg
  %h1 this is the face of user, like a person status
  %h2= @quotation.proverb
  %br
  %h3= link_to @soul.name, soul_path(@soul)
  %br
  = link_to "new", new_soul_quotation_path, class: "btn btn-default btn_bottom_back"
  = link_to "delete", soul_quotation_path(@soul, @quotation), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default btn_bottom_back"

  .body_quotation_show
    .col-xs-3.col-md-3
      #comments
        %h2.comment_count= pluralize(@quotation.quotycomments.count, "Comment")
        - @quotycomments.each do |quotcom|
          .comment
            %p.username= quotcom.soul.name
            %p.content= quotcom.quotycontent
        = render "quotycomments/form"

    .col-xs-8.col-md-8
      - @quotations.each do |quot|
        .user_plate
          .col-xs-3.col-md-3
            .suit
              .suits_fotos
                %h2= link_to quot.author, soul_quotation_path(@soul, quot)
                %h2= link_to quot.proverb, soul_quotation_path(@soul, quot)
                %h2= truncate(quot.description, length: 5)
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
    .col-xs-1.col-md-1
      %p
        =@quotation.get_upvotes.size
        Likes
      %p
        =@quotation.get_downvotes.size
        Likes
      =link_to "Like", like_soul_quotation_path(@soul, @quotation), method: :get
      =link_to "Dislike", dislike_soul_quotation_path(@soul, @quotation), method: :get


  - if @soul.user == current_user
    = link_to "edit", edit_soul_quotation_path, class: "btn btn-default btn_bottom_back"

app/views/quotations/soul_all_projects.html.haml
.body_suits_show
  .col-xs-1.col-md-1

  .col-xs-10.col-md-10
    - @projects.each do |project|
      .user_plate
          .col-xs-3.col-md-3
            .suit
              .suits_fotos
                  %h2= link_to project.title, soul_project_path(@soul, @project)
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3


  .col-xs-1.col-md-1

app/views/quotations/soul_all_quotations.html.haml
.body_suits_show
  .col-xs-1.col-md-1

  .col-xs-10.col-md-10
    - @quotations.each do |quot|
      .user_plate
          .col-xs-3.col-md-3
            .suit
              .suits_fotos
                  %h2= link_to quot.author, soul_project_path(@soul, @quot)
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3


  .col-xs-1.col-md-1