config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :souls do#, path_names: { edit: "soul", update: "soul" }, only: [:show, :edit, :update, :index]
    resources :projects do
      member do
        get "like", to: "projects#upvote"
        get "dislike", to: "projects#downvote"
      end
      resources :projcomments
    end
    resources :purposes do
      member do
        get "like", to: "purposes#upvote"
        get "dislike", to: "purposes#downvote"
      end
      resources :purpcomments
    end
    resources :quotations do
      member do
        get "like", to: "quotations#upvote"
        get "dislike", to: "quotations#downvote"
      end
      resources :quotycomments
    end
    resources :articles do
      member do
        get "like", to: "articles#upvote"
        get "dislike", to: "articles#downvote"
      end
      resources :artcomments
    end
    resources :wishes do
      member do
        get "like", to: "wishes#upvote"
        get "dislike", to: "wishes#downvote"
      end
      resources :wishcomments
    end
    resources :hobbies do
      member do
        get "like", to: "hobbies#upvote"
        get "dislike", to: "hobbies#downvote"
      end
      resources :hobcomments
    end
    resources :experiences
    resources :resumes 
  end

  root "resumes#all_resumes"
  get 'soul_resumes', to: 'resumes#show'

  get 'home', to: 'souls#home'
  get 'cabinet', to: 'souls#cabinet'
  get 'organizer', to: 'souls#organizer'
  get 'all_resumes', to: 'resumes#all_resumes'
  get 'resumes', to: 'resumes#all_resumes'

end

app/models/project.rb
class Project < ActiveRecord::Base
  acts_as_votable
  
  belongs_to :soul
  has_many :projcomments

  has_many :projectteams
  accepts_nested_attributes_for :projectteams, reject_if: proc { |attributes| attributes['team'].blank? }, allow_destroy: true

  has_attached_file :imgproject, styles: { large: "300x300#", medium: "100x100#" }, default_url: "/images/:style/flower4.png"
  validates_attachment_content_type :imgproject, content_type: /\Aimage\/.*\Z/
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :find_soul
	before_action :find_project, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

	def soul_all_projects

	end

	def index
		@projects = Project.where(soul_id: @soul).order("created_at DESC") #.reject { |p| p.id == @project.id}
	end

	def new
		@project = @soul.projects.new
	end

	def create
		@project = @soul.projects.new project_params	
		if @project.save
			redirect_to soul_project_path(@soul, @project)
		else
			render 'new'
		end	
	end

	def show
		@projects = Project.where(soul_id: @soul).order("created_at DESC")  
		@projcomments = Projcomment.where(project_id: @project)
	end

	def edit
		
	end

	def update
		if @project.update project_params
			redirect_to soul_project_path(@soul, @project), notice: "Project was succesfully updated!" 
		else
			render 'edit'
		end
	end

	def destroy
		@project.destroy
		redirect_to soul_projects_path
	end

		def upvote
			@project.upvote_by current_user
			redirect_to :back
		end

		def downvote
			@project.downvote_from current_user
			redirect_to :back
		end

	private

	def project_params
		params.require(:project).permit(:name, :description, :url, :team, :client, :imgproject, 
				projectteams_attributes: [:id, :team, :_destroy])
	end

	def find_soul
		@soul = Soul.find(params[:soul_id])
	end

	def find_project
		@project = Project.find(params[:id])
		#@soul = Soul.find(params[:soul_id])
		#@project = @soul.projects.find(params[:id])
		#@project = Project.find_by(soul_id: params[:project_id])
		#@project = @soul.projects.where(id: params[:id])
		#@message.comments.where(id: params[:id])
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_projects_form.html.haml
.bodybackg
  .col-xs-1.col-md-1
    .btn_back
    = link_to "Back", root_path, class: "btn btn-default"
  .col-xs-10.col-md-10
    .tit_desc_img_block
      = simple_form_for ([@soul, @project]), html: { multipart: true } do |f|
        - if @soul.errors.any?
          #errors
            %p
              = @project.errors.count
              Prevented this project froms saving
            %ul
              - @project.errors.full_messages.each do |msg|
                %li= msg
        .panel-body
          = f.input :name, label: 'Project Name', input_html: { title: "NAME of your project", class: 'form-control'}
          = f.input :description, label: 'Project description', input_html: { class: 'form-control'}
          = f.input :url, label: 'Link', input_html: { title: "NAME of your project", class: 'form-control'}
          = f.input :team, label: 'Project Team', input_html: { class: 'form-control'}
          = f.input :client, label: 'Project Customer', input_html: { title: "NAME of your project", class: 'form-control'}
          = f.input :imgproject, label: 'Attach an image that will be in this project', input_html: { class: 'form-control'}
        .edu_addi_reaso
          .col-xs-12.col-md-12
            %h3 Team:
            #additional_educations
              = f.simple_fields_for :projectteams do |projectteam|
                = render 'projectteam_fields', f: projectteam
              .links
                = link_to_add_association 'Team member', f, :projectteams, class: "btn btn-default add-button"
        %br
        .sub_button

          = f.button :submit, class: "btn btn-primary sub_button"
        .btn_bottom_back
          = link_to "Back", root_path, class: "btn btn-default btn_bottom_back"
  .col-xs-1.col-md-1
  %br

app/views/projects/_projectteam_fields.html.haml
.form-inline.clearfix
  .nested-fields
    .add_form
      .add-button
        = f.input :team, label: 'Team member', input_html: { class: "form-input form-control" }
      .add-button
        = link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/projects/index.html.haml
.body_suits_show
  .col-xs-1.col-md-1
    %br
    = link_to "new", new_soul_project_path, class: "btn btn-default btn_bottom_back"
  .col-xs-10.col-md-10
    - @projects.each do |proj|
      .user_plate
        .col-xs-3.col-md-3
          .suit
            .suits_fotos
              %h2= link_to proj.name, soul_project_path(@soul, proj)#(@projects, @soul)
              %h4
                = proj.projcomments.count
                Comments
        .col-xs-3.col-md-3
        .col-xs-3.col-md-3
        .col-xs-3.col-md-3


  .col-xs-1.col-md-1

app/views/projects/new.html.haml
.caption
  %h1 New Person
  
= render 'projects_form'

app/views/projects/show.html.haml
.bodybackg
  %h1 this is the face of user, like a person status
  %h2= @project.name
  %br
  %h3= link_to @soul.name, soul_path(@soul)
  %br
  = link_to "new", new_soul_project_path, class: "btn btn-default btn_bottom_back"
  = link_to "delete", soul_project_path(@soul, @project), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default btn_bottom_back"

  .body_project_show
    .col-xs-1.col-md-1
      %p
        =@project.get_upvotes.size
        Likes
      %p
        =@project.get_downvotes.size
        Dislikes
      =link_to "Like", like_soul_project_path(@soul, @project), method: :get
      =link_to "Dislike", dislike_soul_project_path(@soul, @project), method: :get

    .col-xs-6.col-md-6
      - @projects.each do |proj|
        .user_plate
          .col-xs-3.col-md-3
            .suit
              .suits_fotos
                %h2= link_to proj.name, soul_project_path(@soul, proj)
                %h2= truncate(proj.description, length: 5)
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3
          .col-xs-3.col-md-3


    .col-xs-2.col-md-2
      #Additional_education:
        %h3 Team:
        %ul
          - @project.projectteams.each do |projectteam|
            %li= projectteam.team 
    .col-xs-3.col-md-3
      #comments
        %h2.comment_count= pluralize(@project.projcomments.count, "Comment")
        - @projcomments.each do |projcomment|
          .comment
            %p.username= projcomment.soul.name
            %p.content= projcomment.projcontent
        = render "projcomments/form"

  - if @soul.user == current_user
    = link_to "edit", edit_soul_project_path, class: "btn btn-default btn_bottom_back"